# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('usage', models.CharField(choices=[('WK', 'Work'), ('SC', 'School'), ('OR', 'Other')], max_length=2)),
                ('plan', models.CharField(choices=[('FR', 'Free'), ('PD', 'Paid')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_disabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latest_contact',
        ),
        migrations.AddField(
            model_name='user',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ON', 'Owner'), ('AD', 'Admin'), ('RU', 'Regular User')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
